pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
        // Add additional back-end build steps here if necessary
      }
    }
    stage('Back-end Testing') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        // Replace with your actual back-end test command
        sh 'mvn test'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
        // Add additional front-end build steps here if necessary
      }
    }
    stage('Front-end Testing') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        // Replace with your actual front-end test command
        sh 'npm test'
      }
    }
    stage('Deployment') {
      // Adjust the agent as per your deployment environment
      agent any
      steps {
        // Replace with your actual deployment commands
        sh 'echo Deploying Application'
        // For example, you might use a script to deploy your application
      }
    }
  }
}
